services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_DEFAULT_USERNAME}
      POSTGRES_PASSWORD: ${DB_DEFAULT_PASSWORD}
      POSTGRES_DB: ${DB_DEFAULT_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
